### ISSUE TITLE
Working with current Ansible (>= 1.9.x[.x]) and CentOS 

### ISSUE THREAD

**Issue by tnt** [dresden-weekly/vagrant-ansible-remote#2]
I've put some crude changes for working with CentOS and current Ansible to [this gist](https://gist.github.com/tnt/f7e5020029b8c65d3f3c). This should be okay for quick testing here and now. But it's not good enough for a PR. And honestly said I would prefer to drop `git-install.sh` at all. The EPEL-/ppa-packages seem to be very up-to-date. 

---

The previous way of installing Ansible with git does not work with the current version. Some considerations:

Until Vagrant 1.8.x the content of the `VERSION` file matched the version number in the respective branch name (`1.8.4` -> `release1.8.4`). Currently (with version 1.9.0) there is only one `stable-1.9` branch but several _sub-versions_. For each of these sub-versions (or sub-sub-versions) there is a tag and the respective commit has a `VERSION`-file with equivalent content as follows:

| tag | VERSION |
| --- | --- |
| `v1.9.0-1` | `1.9.0 1` |
| `v1.9.0-2` | `1.9.0 2` |
| `v1.9.0.1-1` | `1.9.0.1 1` |
| `v1.9.1-0.1rc1` | ? |

So we could replace the `--branch release$ANSIBLE_VERSION` with something like `--branch v$ANSIBLE_VERSION` to install that version and at a later run compare it like `[ "$(<${ANSIBLE_DIR}/VERSION)" != "${ANSIBLE_VERSION/-/ }" ]`. But what really sucks is:

``` bash
set +e
source ${ANSIBLE_DIR}/hacking/env-setup
set -e
```

which seems to fail more or less regularly.

With `pip` installs it would not work to compare a version (or only for minor versions - `pip show ansible | grep -E "^Version: " | grep -Eo "[0-9.]+"` yields `1.9`).

**Comment by arBmind** [comment]
You made some good points here... I would not drop the git-install. You can give it a branch and a version to compare to. Which works fine for trying out betas and master versions. But this is not the desired interface.

Adding pip-install would definitely be a huge improvement.

**Comment by arBmind** [comment]
I added a mirror https://github.com/dresden-weekly/ansible that contains clean git branches that are usable with the git install.

Overall it's not ideal.
We continue to need git install support, to try out custom patches and ansible variations.
The branch names should be more customizable and possibly independent of the VERSION check. See #5

PIP installation option would still be very nice to have. See #4

**Comment by arBmind** [comment]
I close this issue as no progress was made in the last year and we have more focussed follow up tickets.
